spring:
  application:
    name: gateway-server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8090}/

springdoc:
  webjars:
    prefix: /gateway
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /gateway/auth-service/v3/api-docs
        name: Auth Service
      - url: /gateway/room-service/v3/api-docs
        name: Room Service
      - url: /gateway/personal-account/v3/api-docs
        name: Personal Account
    disable-swagger-default-url: true
    path: /gateway