spring:
  application:
    name: gateway-server
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8090}/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /auth-service/v3/api-docs
        name: Auth Service
      - url: /room-service/v3/api-docs
        name: Room Service
      - url: /personal-account/v3/api-docs
        name: Personal Account

