spring:
  liquibase:
    enabled: true

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 8081

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/