spring:
  application:
    name: auth-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8090}/

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      sliding-window-type: count_based
      minimum-number-of-calls: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s

springdoc:
  api-docs:
    path: /v3/api-docs
