spring:
  application:
    name: avatars-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8090}/
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration