package com.example.gamehandlerservice.config

import com.example.personalaccount.database.AccountEntity
import com.example.personalaccount.database.AccountRepository
import com.example.roomservice.service.RoomManager
import org.springframework.http.server.ServerHttpRequest
import org.springframework.http.server.ServerHttpResponse
import org.springframework.stereotype.Component
import org.springframework.web.socket.WebSocketHandler
import org.springframework.web.socket.server.HandshakeInterceptor
import org.springframework.web.util.UriComponentsBuilder

@Component
class UserHandshakeInterceptor(
    private val roomManager: RoomManager,
    private val accountRepository: AccountRepository,
) : HandshakeInterceptor {
    @Throws(Exception::class)
    override fun beforeHandshake(
        request: ServerHttpRequest,
        response: ServerHttpResponse,
        wsHandler: WebSocketHandler,
        attributes: MutableMap<String?, Any?>
    ): Boolean {
        val roomId = UriComponentsBuilder.fromUriString(request.uri.toString()).build()
            .queryParams.getFirst("roomId")?.toLongOrNull() ?: return false

        val userId = extractUserIdFromHeaders(request) ?: return false

        val account = accountRepository.findById(userId.toLong()).orElseGet {
            AccountEntity(0, "autogenerated-name", 0).also { accountRepository.save(it) }
        }

        val room = roomManager.getRoom(roomId) ?: return false
        if (room.bannedPlayers.contains(account.toDto())) {
            return false
        }
        attributes["roomId"] = roomId
        attributes["gameId"] = room.currentGameId
        attributes["accountId"] = account.id
        return true
    }

    override fun afterHandshake(
        request: ServerHttpRequest, response: ServerHttpResponse, wsHandler: WebSocketHandler, exception: Exception?
    ) {
    }

    private fun extractUserIdFromHeaders(request: ServerHttpRequest): String? =
        request.headers["x-user-id"]?.firstOrNull()
}