package com.example.gamehandlerservice.config

import com.example.gamehandlerservice.security.TokenParser
import com.example.personalaccount.database.Account
import com.example.personalaccount.database.AccountRepo
import com.example.roomservice.service.RoomManager
import org.springframework.http.server.ServerHttpRequest
import org.springframework.http.server.ServerHttpResponse
import org.springframework.stereotype.Component
import org.springframework.web.socket.WebSocketHandler
import org.springframework.web.socket.server.HandshakeInterceptor
import org.springframework.web.util.UriComponentsBuilder

@Component
class UserHandshakeInterceptor(
    private val roomManager: RoomManager,
    private val accountRepo: AccountRepo,
    private val tokenParser: TokenParser
) : HandshakeInterceptor {
    @Throws(Exception::class)
    override fun beforeHandshake(
        request: ServerHttpRequest,
        response: ServerHttpResponse,
        wsHandler: WebSocketHandler,
        attributes: MutableMap<String?, Any?>
    ): Boolean {
        val roomId = UriComponentsBuilder.fromUriString(request.uri.toString()).build()
            .queryParams.getFirst("roomId")?.toLongOrNull() ?: return false

        val token = extractJwtTokenFromRequest(request) ?: return false
        val userId = tokenParser.getIdFromToken(token) ?: return false

        val account = accountRepo.findById(userId.toLong()).orElseGet {
            Account("autogenerated-name", 0, true, 0, userId.toLong()).also { accountRepo.save(it) }
        }.apply { active = true }

        attributes["roomId"] = roomId
        attributes["gameId"] = roomManager.getRoom(roomId)?.currentGameId
        attributes["accountId"] = account.id
        return true
    }

    override fun afterHandshake(
        request: ServerHttpRequest, response: ServerHttpResponse, wsHandler: WebSocketHandler, exception: Exception?
    ) {
    }

    private fun extractJwtTokenFromRequest(request: ServerHttpRequest): String? =
        request.headers["Authorization"]?.firstOrNull()?.removePrefix("Bearer ")
}