spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

jwt:
  secret: classpath:certs/private.pem
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

service:
  robot:
    username:
      game-handler
    password:
      kjhkjhkjh

server:
  port: 8082

websocket:
  connect-url: /
  app-prefix: /app
  topic: /topic