version: "3.9"

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka
  db:
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

  personal-account:
    restart: always
    container_name: personal-account
    depends_on:
      - db
      - eureka-server
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
      EUREKA_URL: http://eureka-server:8761/eureka
    build:
          context: ./personal-account
          dockerfile: ./Dockerfile
          platforms:
            - "linux/amd64"
#  app:
#    ports:
#      - "8082:8082"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_HOST: db
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: KfvYuJQ8
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#      platforms:
#        - "linux/amd64"
volumes:
  dbvolume:
