version: "3.9"

services:
  eureka-server:
    container_name: eureka-server
    restart: always
    build: ./eureka-server/
    image: eureka-server
    ports:
      - "8761:8761"
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"

  db1:
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure
  db2:
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql
    ports:
      - "5433:5432"
    expose:
      - 5433
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure
  db3:
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql
    ports:
      - "5434:5432"
    expose:
      - 5434
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure
  db4:
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql
    ports:
      - "5435:5432"
    expose:
      - 5435
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

  personal-account:
    ports:
      - "8090:8090"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-personal-account
      POSTGRES_PORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    depends_on:
      - eureka-server
      - db-personal-account
    build:
      context: ./personal-account
      dockerfile: ./Dockerfile
      platforms:
        - "linux/amd64"

#personal-account:
#  ports:
#    - "8090:8090"
#  environment:
#    POSTGRES_DB: postgres
#    POSTGRES_HOST: db-personal-account
#    POSTGRES_PORT: 5433
#    POSTGRES_USER: postgres
#    POSTGRES_PASSWORD: KfvYuJQ8
#  depends_on:
#    - eureka-server
#    - db-personal-account
#  build:
#    context: ./personal-account
#    dockerfile: ./Dockerfile
#    platforms:
#      - "linux/amd64"


#  app:
#    ports:
#      - "8082:8082"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_HOST: db
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: KfvYuJQ8
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
##      platforms:
##        - "linux/amd64"
volumes:
  dbvolume:
