version: "3.9"

services:
  eureka-server:
    container_name: eureka-server
    restart: always
    build: ./eureka-server/
    image: eureka-server
    ports:
      - "8761:8761"
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"

  personal-account:
    ports:
      - "8090:8090"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-personal-account
      POSTGRES_PORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    depends_on:
      - eureka-server
      - db-personal-account
    build:
      context: ./personal-account
      dockerfile: ./Dockerfile
      platforms:
        - "linux/amd64"

  db-personal-account:
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql
    ports:
      - "5433:5433"
    expose:
      - 5433
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  dbvolume:
