version: "3.9"

services:
  eureka-server:
    restart: always
    build: ./eureka-server/
    image: eureka-server
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"
      - "CONFIG_SERVER_URL=http://config-server:8090"


  personal-account:
    ports:
      - "8083:8083"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-personal-account
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      CONFIG_SERVER_URL: http://config-server:8090
    depends_on:
      - eureka-server
      - db-personal-account
      - config-server

    build:
      dockerfile: ./personal-account/Dockerfile

  auth-service:
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-auth-service
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      CONFIG_SERVER_URL: http://config-server:8090
    depends_on:
      - eureka-server
      - db-auth-service
      - config-server
    build:
      dockerfile: ./auth-service/Dockerfile

  game-handler:
    ports:
      - "8082:8082"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      CONFIG_SERVER_URL: http://config-server:8090
    depends_on:
      - eureka-server
      - config-server
    build:
      dockerfile: ./game-handler/Dockerfile

  room-service:
    ports:
      - "8084:8084"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-room-service
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      CONFIG_SERVER_URL: http://config-server:8090
    depends_on:
      - eureka-server
      - db-room-service
      - config-server
    build:
      dockerfile: ./room-service/Dockerfile

  gateway-server:
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - config-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      CONFIG_SERVER_URL: http://config-server:8090
    build:
      dockerfile: ./gateway-server/Dockerfile

  config-server:
    ports:
      - "8090:8090"
    build:
      dockerfile: ./config-server/Dockerfile

  db-auth-service:
    image: postgres:15.2
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

  db-personal-account:
    image: postgres:15.2
    ports:
      - "5434:5432"
    expose:
      - 5434
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

  db-room-service:
    image: postgres:15.2
    ports:
      - "5435:5432"
    expose:
      - 5435
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure