version: "3.9"

services:
  eureka-server:
    container_name: eureka-server
    restart: always
    build: ./eureka-server/
    image: eureka-server
    ports:
      - "8761:8761"
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka"

  personal-account:
    ports:
      - "8083:8083"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-personal-account
      POSTGRES_PORT: 5434
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    depends_on:
      - eureka-server
      - db-personal-account
    build:
#      context: ./personal-account
      dockerfile: ./personal-account/Dockerfile
#      platforms:
#        - "linux/amd64"

  auth-service:
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-auth-service
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    depends_on:
      - eureka-server
      - db-auth-service
    build:
#      context: ./auth-service
      dockerfile: ./auth-service/Dockerfile

  game-handler:
    ports:
      - "8082:8082"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-game-handler
      POSTGRES_PORT: 5433
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    depends_on:
      - eureka-server
      - db-game-handler
    build:
#      context: ./room-service
      dockerfile: ./game-handler/Dockerfile

  room-service:
    ports:
      - "8084:8084"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST: db-room-service
      POSTGRES_PORT: 5435
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    depends_on:
      - eureka-server
      - db-room-service
    build:
#      context: ./room-service
      dockerfile: ./room-service/Dockerfile

  db-auth-service:
    image: postgres:15.2
#    volumes:
#      - dbvolume-auth-service:/var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

  db-game-handler:
    image: postgres:15.2
#    volumes:
#      - dbvolume-game-handler:/var/lib/postgresql
    ports:
      - "5433:5432"
    expose:
      - 5433
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

  db-personal-account:
    image: postgres:15.2
#    volumes:
#      - dbvolume:/var/lib/postgresql
    ports:
      - "5434:5432"
    expose:
      - 5434
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure
  db-room-service:
    image: postgres:15.2
#    volumes:
#      - dbvolume:/var/lib/postgresql
    ports:
      - "5435:5432"
    expose:
      - 5435
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KfvYuJQ8
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  dbvolume:
