spring:
  liquibase:
    enabled: true

  application:
    name: personal-account

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

jwt:
  secret: classpath:certs/private.pem
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
server:
  port: 8090

websocket:
  connect-url: /
  app-prefix: /app
  topic: /topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/