spring:
  liquibase:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}

server:
  port: 8082
