spring:
  liquibase:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          vk:
            client-id: 51661254
            client-secret: kCqCbjr5VYpMHItBZtSu
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: email,notify
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize?revoke=1
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get?v=8.1&fields=photo_max
            user-name-attribute: first_name

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

jwt:
  secret: classpath:certs/private.pem
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
server:
  port: 8080

websocket:
  connect-url: /
  app-prefix: /app
  topic: /topic