feign:
  client:
    config:
      room-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptors:
          - com.example.common.interceptor.AuthRequestInterceptor

feign:
  client:
    config:
      personal-account:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptors:
          - com.example.common.interceptor.AuthRequestInterceptor
