feign:
  client:
    config:
      room-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: debug
        requestInterceptors:
          - com.example.common.interceptor.AuthRequestInterceptor
      personal-account:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: debug
        requestInterceptors:
          - com.example.common.interceptor.AuthRequestInterceptor
