spring:
  liquibase:
    enabled: true

  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  main:
    web-application-type: reactive

server:
  port: 8081

service:
  robot:
    username:
      auth-service
    password:
      auth-service

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19090,localhost:19091,localhost:19092}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    path: /v3/api-docs