spring:
  application:
    name: gateway-server
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}