spring:
  application:
    name: room-service
  liquibase:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5435}/${POSTGRES_DB:postgres}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5435}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:KfvYuJQ8}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  main:
    web-application-type: reactive

service:
  robot:
    username: room-service
    password: qweqweqwe

server:
  port: 8084

feign:
  client:
    config:
      room-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: debug
        requestInterceptors:
          - com.example.common.interceptor.AuthRequestInterceptor
      personal-account:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: debug
        requestInterceptors:
          - com.example.common.interceptor.AuthRequestInterceptor

rsa:
  public-key: classpath:certs/public.pem

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19090,localhost:19091,localhost:19092}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /v3/api-docs