name: Build and deploy

on: push

jobs:
  push-service-image:
    name: Push service image to registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - eureka-server
          - config-server
          - gateway-server
          - game-handler
          - auth-service
          - personal-account
          - room-service
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Login to YC container registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build image
        run: make ${{ matrix.service }} push
#  deploy:
#    name: Deploy to PROD
#    runs-on: ubuntu-latest
#    needs:
#      - push-service-image
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v4
#      - name: Login to YC container registry
#        uses: yc-actions/yc-cr-login@v2